Support DB seeding from external and internal apps (#9)
https://eaflood.atlassian.net/browse/WATER-5744

When we [split **water-abstraction-system** into engine and app](https://github.com/DEFRA/water-abstraction-system/pull/3581), we wanted to keep the DB centrally managed, as both [water-abstraction-external](https://github.com/DEFRA/water-abstraction-external) and [water-abstraction-internal](https://github.com/DEFRA/water-abstraction-system) will be using the same DB.

We managed to figure this out for migrations, but mistakenly dropped seeding.

This change is what's needed to get it working again. We tried running the command from the (`"seed": "water-knex seed:run"`) apps, but both reported the same error.

```
Error: Invalid seed file: /home/repos/water-abstraction-system/node_modules/water-abstraction-engine/db/seeds/01-regions.seed.js must have a seed function
    at Seeder._validateSeedStructure (/home/repos/water-abstraction-system/node_modules/knex/lib/migrations/seed/Seeder.js:57:13)
    at async Seeder._runSeeds (/home/repos/water-abstraction-system/node_modules/knex/lib/migrations/seed/Seeder.js:49:7)
```

We're not sure why this wasn't an issue before, as we have been using `export default async function seed()` for some time. It might have been the switch to an engine, but then it's been a long time since we've run the seed, so it's as likely to be a change in **Knex**.

Either way, dropping the `default` solves the problem!